// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMVhxBt2EFqJbfUSqwwXYlEiDFSVJaIwI',
    appId: '1:879015889552:web:fbd26b4056e4722ee26615',
    messagingSenderId: '879015889552',
    projectId: 'simple-bank-manager-2025',
    authDomain: 'simple-bank-manager-2025.firebaseapp.com',
    storageBucket: 'simple-bank-manager-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbXTMIZhvmkZPOc21tOp43Xetg5aoQPIs',
    appId: '1:879015889552:android:de0e9f29853f471de26615',
    messagingSenderId: '879015889552',
    projectId: 'simple-bank-manager-2025',
    storageBucket: 'simple-bank-manager-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtp4QC7-nOnzR6aDeE6iAUih9GPnezbIM',
    appId: '1:879015889552:ios:fb2e02eff410efafe26615',
    messagingSenderId: '879015889552',
    projectId: 'simple-bank-manager-2025',
    storageBucket: 'simple-bank-manager-2025.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtp4QC7-nOnzR6aDeE6iAUih9GPnezbIM',
    appId: '1:879015889552:ios:fb2e02eff410efafe26615',
    messagingSenderId: '879015889552',
    projectId: 'simple-bank-manager-2025',
    storageBucket: 'simple-bank-manager-2025.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMVhxBt2EFqJbfUSqwwXYlEiDFSVJaIwI',
    appId: '1:879015889552:web:86ae336bed0a03e6e26615',
    messagingSenderId: '879015889552',
    projectId: 'simple-bank-manager-2025',
    authDomain: 'simple-bank-manager-2025.firebaseapp.com',
    storageBucket: 'simple-bank-manager-2025.firebasestorage.app',
  );

}