// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWtFMuIAisuPYqFclbpDXB0fj6IzlA6RQ',
    appId: '1:672156119487:web:4745d143b2f3de48e6f10a',
    messagingSenderId: '672156119487',
    projectId: 'simple-bank-manager-2',
    authDomain: 'simple-bank-manager-2.firebaseapp.com',
    storageBucket: 'simple-bank-manager-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrpzM92SkRWLpYjjzpR1pkSgKxJsiw3hk',
    appId: '1:672156119487:android:0b49b367250b6bd4e6f10a',
    messagingSenderId: '672156119487',
    projectId: 'simple-bank-manager-2',
    storageBucket: 'simple-bank-manager-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNXKximbu4saKvOzz2LKqWivUZgqLp6CQ',
    appId: '1:672156119487:ios:296f52c11a31ebf1e6f10a',
    messagingSenderId: '672156119487',
    projectId: 'simple-bank-manager-2',
    storageBucket: 'simple-bank-manager-2.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNXKximbu4saKvOzz2LKqWivUZgqLp6CQ',
    appId: '1:672156119487:ios:296f52c11a31ebf1e6f10a',
    messagingSenderId: '672156119487',
    projectId: 'simple-bank-manager-2',
    storageBucket: 'simple-bank-manager-2.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWtFMuIAisuPYqFclbpDXB0fj6IzlA6RQ',
    appId: '1:672156119487:web:b2a7f274e27b97e3e6f10a',
    messagingSenderId: '672156119487',
    projectId: 'simple-bank-manager-2',
    authDomain: 'simple-bank-manager-2.firebaseapp.com',
    storageBucket: 'simple-bank-manager-2.firebasestorage.app',
  );
}
